---
👨‍💻 **Author:** Jay Prajapati  
📘 **Project:** NumPy for ML  
📅 **Created:** August 2025  
---


# NumPy Basics 🚀

This notebook introduces the **fundamentals of NumPy**, the core library for numerical computing in Python.  
We’ll explore:

1. Array creation  
2. Array attributes  
3. Special arrays  
4. Indexing & slicing  
5. Basic operations  
6. Reshaping  

👉 Why this matters for ML/AI:  
Every machine learning model relies on **matrices and vectors** (tensors). NumPy provides the foundation for these operations efficiently.


In [43]:
import numpy as np

print("Numpy version:", np.__version__)

Numpy version: 1.26.4


## 1. Creating Arrays

NumPy’s core data structure is the **ndarray** (N-dimensional array).  
Think of it as a supercharged list that supports mathematical operations directly.

In [44]:
# 1D array (vector)
vector = np.array([1, 2, 3, 4, 5])  

# 2D array (matrix)
matrix = np.array([[1, 2, 3], 
               [4, 5, 6]])

# 3D array (tensor) 
tensor = np.array([[[1], [2], [3]], 
                [[4], [5], [6]]])  

print("Vector (1D):\n", vector)
print("\nMatrix (2D):\n", matrix)
print("\nTensor (3D):\n", tensor)

Vector (1D):
 [1 2 3 4 5]

Matrix (2D):
 [[1 2 3]
 [4 5 6]]

Tensor (3D):
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


## 2. Array Attributes

Every array has important properties:
- **Shape** → dimensions of the array  
- **Size** → total number of elements  
- **Data type (dtype)** → type of values stored  
- **Number of dimensions (ndim)**  

These are critical when working with ML models, since data must be in the correct **shape**.


In [45]:
print("Matrix shape  :", matrix.shape)  # rows x cols
print("Matrix Size   :", matrix.size)   # total number of elements
print("Data type     :", matrix.dtype)   # type of elements
print("Dimensions    :", matrix.ndim) # 1D / 2D / 3D etc.

Matrix shape  : (2, 3)
Matrix Size   : 6
Data type     : int32
Dimensions    : 2


## 3. Special Arrays

NumPy provides functions to create commonly used arrays:
- **Zeros & Ones** → useful for initializing weights  
- **Identity matrix** → common in linear algebra  
- **Random numbers** → often used for ML initialization & data simulation


In [46]:
# common initializations
zeros_matrix = np.zeros((3,3))
ones_matrix = np.ones((2,4))
identity_matrix = np.eye(4)
random_matrix = np.random.rand(3,3)

print("Zeros matrix:\n", zeros_matrix)
print("\nOnes matirx:\n", ones_matrix)
print("\nIdentity matrix:\n", identity_matrix)
print("\nRandom matrix:\n", random_matrix)

Zeros matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones matirx:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random matrix:
 [[0.69182024 0.68825159 0.28637258]
 [0.29812652 0.64601617 0.42756321]
 [0.40011527 0.49441159 0.93698213]]


## 4. Indexing & Slicing

Accessing elements of arrays is critical for **data preprocessing**.  
Similar to Python lists, but more powerful with **multidimensional slicing**.

In [32]:
arr = np.arange(10)  # array [0,1,2,.....9]
print("Array:", arr)

# Accessing elements 
print("First element    :", arr[0])
print("Last element     :", arr[-1])

#slicing
print("Slice [2:7]      :", arr[2:7]) # elements at index 2-6
print("Every 2nd element:", arr[::2]) # step = 2

Array: [0 1 2 3 4 5 6 7 8 9]
First element    : 0
Last element     : 9
Slice [2:7]      : [2 3 4 5 6]
Every 2nd element: [0 2 4 6 8]


## 5. Basic Operations

NumPy allows **vectorized operations** (no loops needed):
- Element-wise operations (`+`, `*`)  
- Dot products (essential for ML models)  
- Power operations  

👉 This efficiency is why ML libraries like TensorFlow & PyTorch are built on top of NumPy.


In [36]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print("X =", x)
print("y =", y)

# Element wise operations
print("\nAddition      :", x + y)
print("Multiplication:", x * y)

# Dot product (important in ML for weighted sums)
print("x dot y =", np.dot(x,y))

# Element-wise power
print("x squared =", x**2)


X = [1 2 3]
y = [4 5 6]

Addition      : [5 7 9]
Multiplication: [ 4 10 18]
x dot y = 32
x squared = [1 4 9]


## 6. Reshaping

Data often needs to be **reshaped** into the correct format:  
- A dataset may come as a flat array but needs to be shaped into (samples, features).  
- Reshaping is also key when feeding data into ML models.


In [37]:
arr = np.arange(1,13)  # [1..12]
reshaped = arr.reshape(3,4)

print("Original (1D):", arr)
print("\nReshaped (3x4):\n", reshaped)

Original (1D): [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 7. Practical Example in ML Context 🎯

So far, we’ve looked at arrays in isolation.  
But in **Machine Learning**, data is usually represented as:

- **Feature Matrix (X):** rows = samples, columns = features  
- **Target Vector (y):** labels or values we want to predict  

For example, consider a simple classification problem (like Iris dataset).  
We’ll represent **4 samples** with **3 features each**, and their class labels.


In [42]:
# Example: Feature matrix (x) and target vector (y) for ML

#suppose we have 4 samples and 3 features each

X = np.array([[5.1, 3.5, 1.4],
             [4.9, 3.0, 1.4],
             [6.2, 3.4, 5.4],
             [5.9, 3.0, 5.1]])

# Target labels (classification: 0 = class A, 1 = class B)
y = np.array([0, 0, 1, 1])

print("Feature matrix (X):\n", X)
print("\nTarget vector (y):", y)
print("\nshape of X:", X.shape)  # (samples, features)
print("Shape of y:", y.shape) # (samples,)

Feature matrix (X):
 [[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [6.2 3.4 5.4]
 [5.9 3.  5.1]]

Target vector (y): [0 0 1 1]

shape of X: (4, 3)
Shape of y: (4,)


## ✅ Summary

In this notebook, we learned:

- How to create NumPy arrays (1D, 2D, 3D)  
- Array attributes (shape, size, dtype, ndim)  
- Special arrays (zeros, ones, identity, random)  
- Indexing & slicing  
- Basic operations (addition, multiplication, dot product)  
- Reshaping arrays  
- A **practical ML example** (feature matrix `X` + target vector `y`)  

👉 These operations are the **foundation for ML/AI workflows**,  
where data is usually represented as arrays/tensors.  

🔜 In the next notebook, we’ll cover **Broadcasting & Advanced Array Operations**.
