# 📘 Notebook 3: Linear Algebra with NumPy  

---

## 1️⃣ Introduction  

Linear algebra is at the **heart of Machine Learning**.  
Most ML algorithms (Linear Regression, PCA, Neural Nets) are just **matrix operations**.  

We’ll cover:  
- Vector & Matrix operations  
- Transpose, Inverse, Determinant  
- Eigenvalues/Eigenvectors  
- Singular Value Decomposition (SVD)  
- ML Example → Linear Regression using the Normal Equation  

---

## 1️⃣ Vectors & Dot Product

The **dot product** is a fundamental operation in linear algebra.

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# Method 1
dot1 = np.dot(a,b)

# Method 2 (Python 3.5+ operator)
dot2 = a @ b

print("Dot Product (np.dot):", dot1)
print("Dot Product (@operator):", dot2)

Dot Product (np.dot): 32
Dot Product (@operator): 32


In [4]:
A = np.array([[1,2],
             [3,4]])

B = np.array([[5, 6],
             [7,8]])

C = np.matmul(A, B)  # or A @ B
print("Matrix Multiplication:\n", C)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [5]:
M = np.array([[1,2,3],
              [4,5,6]])

print("Original:\n", M)
print("Transpose:\n", M.T)

Original:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [6]:
M = np.array([[4,7],
             [2,6]])

det = np.linalg.det(M)
inv = np.linalg.inv(M)

print("Determinant:",det)
print("Inverse:\n", inv)

Determinant: 10.000000000000002
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [7]:
M = np.array([[4, -2],
              [1, 1]])

eig_vals, eig_vecs = np.linalg.eig(M)

print("Eigenvalue:\n", eig_vals)
print("Eigenvectors:\n", eig_vecs)

Eigenvalue:
 [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [9]:
M = np.array([[3, 1, 1],
             [-1, 3, 1]])

U, S, Vt = np.linalg.svd(M)

print("U:\n", U)
print("Singular Values:\n", 5)
print("V^T:\n", Vt)

U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular Values:
 5
V^T:
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.26260748e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [ ]:
# Dataset: predicting y from x
X = np.array([1, 2, 3, 4, 5])
y = np.array([3, 4, 2, 5, 6])

# Reshape X into feature matrix with bias term
X_b = np.c_[np.ones((len(X), 1)), X.reshape(-1, 1)]

# Normal Equation
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

print("Theta (Intercept, Slope):", theta)


Theta (Intercept, Slope): [1.9 0.7]


In [16]:
model = LinearRegression()
model.fit(X.reshape(-1, 1), y)

print("Sklearn Coefficients:", model.intercept_, model.coef_[0])

Sklearn Coefficients: 1.9000000000000004 0.6999999999999998
