1️⃣ Generating Synthetic Data

In [6]:
import numpy as np

# Seed for reproducibility
np.random.seed(42)

# Features: 100 samples, 3 features
X = np.random.rand(100, 3)

# True coefficients
true_w = np.array([3, 5, -2])

# Target with noise
y = X @ true_w + np.random.randn(100) * 0.5

print("Feature matrix X shape:", X.shape)
print("Target vector y shape:", y.shape)


Feature matrix X shape: (100, 3)
Target vector y shape: (100,)


2️⃣ Feature Scaling & Normalization

In [7]:
# Min-Max Scaling
X_min = X.min(axis=0)
X_max = X.max(axis=0)
X_scaled = (X - X_min) / (X_max - X_min)

# Standardization
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
X_standardized = (X - X_mean) / X_std

print("First 5 samples after standardization:\n", X_standardized[:5])

First 5 samples after standardization:
 [[-0.35958026  1.4198383   0.82216804]
 [ 0.42811633 -1.15479213 -1.18711031]
 [-1.47181267  1.14595419  0.36561862]
 [ 0.81266807 -1.59356748  1.65209819]
 [ 1.24978474 -0.97232681 -1.09700508]]


3️⃣ Train/Test Split

In [8]:
# Shuffle indices
indices = np.arange(X.shape[0])
np.random.shuffle(indices)

# Split 80% train / 20% test
train_size = int(0.8 * X.shape[0])
train_idx, test_idx = indices[:train_size], indices[train_size:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print("Train shape:", X_train.shape, y_train.shape)
print("Test shape:", X_test.shape, y_test.shape)

Train shape: (80, 3) (80,)
Test shape: (20, 3) (20,)


4️⃣ Linear Regression

In [9]:
# Closed-form solution (Normal Equation)
w_hat = np.linalg.inv(X_train.T @ X_train) @ X_train.T @ y_train

# Predictions
y_pred = X_test @ w_hat

# Mean Squared Error
mse = np.mean((y_test - y_pred)**2)
print("Learned coefficients:", w_hat)
print("Test MSE:", mse)

Learned coefficients: [ 3.10335623  4.88877018 -1.86726428]
Test MSE: 0.27073697380442907


5️⃣ Vectorized Operations & Efficiency

In [10]:
# Example: compute Euclidean distance between all points
dists = np.sqrt(np.sum((X_train[:, np.newaxis, :] - X_train[np.newaxis, :, :])**2, axis=2))
print("Distance matrix shape:", dists.shape)

Distance matrix shape: (80, 80)


6️⃣ Summary

In this notebook, we learned:

How to generate synthetic ML datasets

Feature scaling & normalization

Train/test splitting without libraries

Implementing linear regression from scratch

Vectorized operations for efficiency

👉 Next: NumPy + Matplotlib for ML Visualization or Introduction to scikit-learn workflows.